### PR TITLE
Take in account the capability to get default attribute options. $type was not …

### PR DESCRIPTION
**Pull request by diglin**
…provided into the method _getCombinedKey

### CODE REVIEW

**Comment by Flyingmana** [comment]
looks fine for me

**Comment by quafzi** [comment]
@diglin @Flyingmana Thank you!

I'm still looking for a new maintainer of this module. It would be great to turn it into a Firegento module, therefore I already adapted the Firegento coding style rules in  [firegento](https://github.com/quafzi/magento-performance-tweaks/tree/firegento) branch. Anyone interested?

**Comment by Flyingmana** [comment]
@quafzi if Firegento does not work out, I still offer to take the maintaining over as part of @Cotya

**Comment by diglin** [comment]
@therouv is one of the person who can confirm that or not. I use your module very often so I could be the maintainer. I have also a module which waits to be confirmed for a Firegento namespace changes

**Comment by therouv** [comment]
I'd vote for a move to FireGento namespace because I think this module would be a great addition.
 
I have some questions/remarks though which I will post (probably/at the latest) Wednesday (public holiday in Germany).

**Comment by therouv** [comment]
Hi @quafzi great module, thanks! 
My questions/remarks:
* With which Magento versions is this module supposed to work? We should add a hint in the README with the supported versions.
  * Ideally there will be tests for all changes and let travis build for different Magento/PHP versions.
* The Branch `firegento` should be updated with the latest changes from `master` branch.
* License file in `firegento` branch should be updated to GPL as well.

**Pull request merged**
